const LoaderActionTypes = {
  SET_LOADER_IS_VISIBLE: 'SET_LOADER_IS_VISIBLE',
  SET_LOADER_IS_LOADING: 'SET_LOADER_IS_LOADING',
  SET_LOADER_TEXT: 'SET_LOADER_TEXT',
};

export default LoaderActionTypes;
