const DatabasesActionTypes = {
  ADD_NEW_RECORD_TO_DB: 'ADD_NEW_RECORD_TO_DB',
  FETCH_BALANCE_DATA: 'FETCH_BALANCE_DATA',
  FETCH_BALANCE_DATA_SUCCESS: 'FETCH_BALANCE_DATA_SUCCESS',
  FETCH_SAVINGS_DATA: 'FETCH_SAVINGS_DATA',
  FETCH_SAVINGS_DATA_SUCCESS: 'FETCH_SAVINGS_DATA_SUCCESS',
};

export type ACTIONTYPE = {
  type: 'ADD_NEW_RECORD_TO_DB' | 'FETCH_BALANCE_DATA';
};

export default DatabasesActionTypes;
